{{- if .Values.global.persistence.manualPV -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logodal-db-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.primary.persistence.size | default "10Gi" }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClass | default "logodal-db-local" }}
  hostPath:
    path: /mnt/k8s-volumes/logodal-db
    type: DirectoryOrCreate
{{- end -}}

